### ISSUE TITLE
DOnt mint 

### ISSUE THREAD

**Issue by gsandoval22** [GottliebGlob/candy-machine-ui#1]
I love this  Ui but i cant mint!!.. I can't find the error, pressing the button does the mint but only charges the fees and when I update the page the supply is restored

**Comment by crusaderincode** [comment]
The error is known. I'll fix it as soon as possible. Stay tuned for new release

**Comment by crusaderincode** [comment]
> I love this Ui but i cant mint!!.. I can't find the error, pressing the button does the mint but only charges the fees and when I update the page the supply is restored

Fixed!
